import React from 'react';
import { Link } from 'react-router-dom';
import Navbar from './Navbar';
import Footer from './Footer';
import '../../styles/landing.css';

function TermsPage() {
  return (
    <div className="landing-wrapper">
      <Navbar currentPage="terms" />
      
      <div className="ph" style={{ marginTop: 'calc(var(--bh) + var(--nh))' }}>
        <div className="phi" style={{ background: 'var(--bg2)' }} />
        <div className="pho" />
        <div className="phc">
          <div className="bc">Legal</div>
          <h1 className="pht">Terms of Service</h1>
          <p className="phs">Last updated: December 2025</p>
        </div>
      </div>

      <div className="legal-page">
        <div className="cn">
          <div className="legal-content" data-testid="terms-content">
            <p className="legal-meta">
              These Terms of Service ("Terms") govern your use of the Intermaven platform and services. By accessing or using Intermaven, you agree to be bound by these Terms.
            </p>

            <h2>1. Account Terms</h2>
            <h3>1.1 Eligibility</h3>
            <p>
              You must be at least 18 years old to create an account on Intermaven. By registering, you represent and warrant that you meet this age requirement and have the legal capacity to enter into these Terms.
            </p>

            <h3>1.2 Account Security</h3>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must immediately notify us of any unauthorized use of your account.
            </p>

            <h3>1.3 Accurate Information</h3>
            <p>
              You agree to provide accurate, current, and complete information during registration and to update such information to keep it accurate, current, and complete.
            </p>

            <h2>2. Acceptable Use</h2>
            <h3>2.1 Permitted Uses</h3>
            <p>
              You may use Intermaven for lawful purposes only. Our platform is designed for African creatives and entrepreneurs to build their brands, create content, and grow their businesses.
            </p>

            <h3>2.2 Prohibited Activities</h3>
            <p>You may not:</p>
            <ul>
              <li>Use the service for any illegal purpose or in violation of any laws</li>
              <li>Attempt to gain unauthorized access to any portion of the service</li>
              <li>Interfere with or disrupt the service or servers</li>
              <li>Use AI-generated content to deceive, defraud, or harm others</li>
              <li>Create content that is hateful, discriminatory, or promotes violence</li>
              <li>Resell or redistribute the service without authorization</li>
              <li>Violate intellectual property rights of others</li>
            </ul>

            <h3>2.3 AI-Generated Content</h3>
            <p>
              Content generated by our AI tools is for your personal or business use. You are responsible for reviewing and editing AI outputs before use. We do not guarantee the accuracy, appropriateness, or legal compliance of AI-generated content.
            </p>

            <h2>3. Credits & Payments</h2>
            <h3>3.1 Credit System</h3>
            <p>
              Intermaven operates on a credit-based system. Each AI tool consumes a specific number of credits per use. Credit costs are displayed before each generation.
            </p>
            <ul>
              <li><strong>Free Plan:</strong> 150 credits, valid for 90 days</li>
              <li><strong>Creator Plan:</strong> 600 credits (KES 500), never expire</li>
              <li><strong>Pro Plan:</strong> 2,500 credits (KES 1,500), never expire</li>
            </ul>

            <h3>3.2 Payments</h3>
            <p>
              Payments are processed through Pesapal, supporting M-Pesa and card payments. All prices are in Kenyan Shillings (KES). Payments are non-refundable except as required by law.
            </p>

            <h3>3.3 Refund Policy</h3>
            <p>
              Due to the nature of digital services, we generally do not offer refunds for purchased credits. However, we may offer refunds or credit adjustments at our discretion in cases of technical issues or service failures.
            </p>

            <h2>4. Intellectual Property</h2>
            <h3>4.1 Your Content</h3>
            <p>
              You retain ownership of the content you input into our platform. By using our service, you grant us a limited license to process this content to provide our services.
            </p>

            <h3>4.2 AI Output Ownership</h3>
            <p>
              Content generated by our AI tools using your inputs is owned by you, subject to our platform's terms. You may use AI-generated content for personal and commercial purposes.
            </p>

            <h3>4.3 Platform Rights</h3>
            <p>
              Intermaven and its licensors retain all rights to the platform, including its design, features, and underlying technology. You may not copy, modify, or distribute our platform or its components.
            </p>

            <h2>5. Limitation of Liability</h2>
            <h3>5.1 Service Availability</h3>
            <p>
              We strive to maintain high service availability but do not guarantee uninterrupted access. We may perform maintenance or updates that temporarily affect service availability.
            </p>

            <h3>5.2 Disclaimer</h3>
            <p>
              THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>

            <h3>5.3 Liability Cap</h3>
            <p>
              Our total liability to you for any claims arising from your use of the service shall not exceed the amount you paid us in the 12 months preceding the claim.
            </p>

            <h2>6. Termination</h2>
            <h3>6.1 By You</h3>
            <p>
              You may close your account at any time by contacting support. Unused credits are non-refundable upon account closure.
            </p>

            <h3>6.2 By Us</h3>
            <p>
              We may suspend or terminate your account for violations of these Terms or for any reason with reasonable notice. In cases of serious violations, we may terminate immediately without notice.
            </p>

            <h3>6.3 Effect of Termination</h3>
            <p>
              Upon termination, your access to the service will cease. We may retain your data for legal compliance purposes but will delete it upon request, subject to legal obligations.
            </p>

            <h2>7. Governing Law</h2>
            <p>
              These Terms are governed by the laws of Kenya. Any disputes arising from these Terms shall be resolved in the courts of Nairobi, Kenya.
            </p>

            <h2>8. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. We will notify you of material changes via email or through the platform. Continued use after changes constitutes acceptance of the updated Terms.
            </p>

            <h2>9. Contact Us</h2>
            <p>
              If you have questions about these Terms, please contact us at:
            </p>
            <ul>
              <li>Email: legal@intermaven.io</li>
              <li>Address: Nairobi, Kenya</li>
            </ul>

            <div style={{ marginTop: '40px', paddingTop: '24px', borderTop: '1px solid var(--b1)' }}>
              <Link to="/" className="hbp" style={{ textDecoration: 'none' }}>
                ← Back to Home
              </Link>
            </div>
          </div>
        </div>
      </div>

      <Footer />
    </div>
  );
}

export default TermsPage;
